---
# Role tasks

- name: Setup configuration options
  lineinfile:
    path: "{{ yum_conf_file }}"
    regexp: "^{{ yum_conf_item.option }}="
    line: "{{ yum_conf_item.option }}={{ yum_conf_item.value }}"
    state: "{{ yum_conf_item.state | default('present') }}"
  loop: "{{ yum_conf_options }}"
  loop_control:
    loop_var: yum_conf_item
    label: "{{ yum_conf_item.option }}"
