---

- name: Verify
  hosts: molecule_hosts
  gather_facts: yes
  tasks:
    - name: Gather config file content
      command: >-
        cat
        {{ (ansible_facts.distribution_major_version is version("7", ">"))
           | ternary("/etc/dnf/dnf.conf", "/etc/yum.conf") }}
      changed_when: no
      register: config_file_result

    - name: Assert config options are valid
      assert:
        that:
          - config_file_result.stdout is search("logfile=/var/log/yum.log")
          - config_file_result.stdout is search("gpgcheck=0")
          - config_file_result.stdout is not search("cachedir")
